# nginx
---
- name: Add php5 PPA
  apt_repository: repo='ppa:ondrej/php5'

- name: Install packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - apache2-utils     
    - nginx
    - ssl-cert
    - php5
    - php5-fpm
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-mcrypt
    - php5-mysql
  tags:
    - skip_after_first_run

- name: turn off PHP output buffering
  ini_file: dest=/etc/php5/fpm/php.ini section=PHP option=output_buffering value=Off 

#- name: set cgi.fix_pathinfo
#  ini_file: dest=/etc/php5/fpm/php.ini section=PHP option=output_buffering value=Off 

- name: Apply config template
  template:
    src: nginx-ssl.conf
    dest: "/etc/nginx/sites-available/{{ inventory_hostname }}"

- name: Enable nginx conf
  file: 
    path: "/etc/nginx/sites-enabled/{{ inventory_hostname }}"
    state: link
    src: "/etc/nginx/sites-available/{{ inventory_hostname }}"
  notify: restart nginx
  notify: restart php5-fpm     
