# apache2
---
- name: Add php5 PPA
  apt_repository: repo='ppa:ondrej/php5'
  
 - name: Install packages
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
    - apache2
    - apache2-utils
    - php5
    - php5-curl
    - php5-gd
    - php5-geoip
    - php5-mcrypt
    - php5-mysql
    - libapache2-mod-php5

- name: turn off PHP output buffering
  ini_file: dest=/etc/php5/apache2/php.ini section=PHP option=output_buffering value=Off 

- name: Apply apache2 template (apacheSSL.conf)
  template: src=apacheSSL.conf dest=/etc/apache2/sites-available/{{ domain }}.conf force=yes

- name: Enable apache2 modules
  apache2_module: name={{ item }} state=present
  with_items: 
    - rewrite
    - request
    - headers 
    - proxy_http
    - proxy
    - auth_form
    - session_cookie
    - session_crypto
    - ssl

- name: Disable apache2 default site
  command: /bin/rm /etc/apache2/sites-enabled/000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf

- name: Disable apache2 default site (SSL)
  command: /bin/rm /etc/apache2/sites-enabled/000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/default-ssl.conf 

- name: Enable Pydio site
  command: a2ensite {{ domain }}
  args:
    creates: /etc/apache2/sites-enabled/{{ domain }}.conf
