---
- name: copy ruTorrent update script
  copy: src=update-rutorrent dest=/usr/local/bin/update-rutorrent mode=0777

- name: Download ruTorrent to /var/www/pydio/rutorrent
  command: /usr/local/bin/update-rutorrent
  args:
    creates: /var/www/pydio/rutorrent

- name: Apply config template
  template: src=config.php dest=/var/www/pydio/rutorrent/conf/config.php owner=www-data group=www-data 

- name: Copy autowatch config file
  copy: src=autotools-conf.php dest=/var/www/pydio/rutorrent/plugins/autotools/conf.php force=yes 
  
- name: Copy autowatch config file
  copy: src=screenshots-conf.php dest=/var/www/pydio/rutorrent/plugins/screenshots/conf.php force=yes 

- name: Copy unpack config file 
  copy: src=unpack-conf.php dest=/var/www/pydio/rutorrent/plugins/unpack/conf.php force=yes 

- name: Create password
  command: "htpasswd -cb /etc/apache2/passwd {{ web_user }} {{ web_password }}"  
  args:
    creates: /etc/apache2/passwd

- name: Copy over html files
  copy: src=auth.tar.gz dest=/tmp/auth.tar.gz

- name: Extract auth components
  command: "/usr/bin/bsdtar -xf /tmp/auth.tar.gz --strip-components 1"
  args:
    creates: /var/www/pydio/login.html
    chdir: /var/www/pydio 
