---

#name: Add ffmpeg PPA
  #apt_repository: repo='ppa:kirillshkrogalev/ffmpeg-next'
  #tags:
    #- skip_after_first_run

- name: Install deps and utils 
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - automake
    - build-essential
    - bsdtar  
    - curl
    - git-core
    - libav-tools
    - libcppunit-dev
    - libcurl4-openssl-dev
    - libncurses5-dev
    - libsigc++-2.0-dev
    - libtool
    - mediainfo
    - subversion
    - zip
    - unrar-free
    - unzip 
  tags:
    - skip_after_first_run

